# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 328288caa56a0009d2dba1cfc4ee49273bb912db8339a23fba9b7e4a1a41ed79ce03bba10781e94007ea6d1512dc902ff2c803cff1d11fe3973946c03e766ade

test:
  secret_key_base: a21ad80b1e0930c20a3062780c0111f5f3e8ef48414046fcf216cad8a27f7e7865e206c6b8161cdfee2fac36bcfc7e3cce929772a7bcb87a1e809135ec25f3e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
